webformat/employees/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

webformat/webformat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('', include('ticketing.urls')),
    path("accounts/", include("employees.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

webformat/ticketing/models.py
from msilib.schema import Registry
from pyexpat import model
from statistics import mode
from django.db import models
from django.conf import settings
from django.urls import reverse
from enum import IntEnum

# Create your models here.

class Team(models.Model):
  members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='teams')
  name = models.CharField(max_length=30)
  description = models.TextField(null=True)

  def __string__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Project(models.Model):
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  pm = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pm')
  name = models.CharField(max_length=30)
  description = models.TextField(null=True)

  def __string__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Task(models.Model):

  class Status(IntEnum):
    TO_DO = 1
    IN_PROGRESS = 2
    STAGE = 3
    DONE = 4

    @classmethod
    def choices(cls):
      return [(key.value, key.name) for key in cls]

  description = models.CharField(max_length=30)
  status = models.IntegerField(choices=Status.choices(), default=Status.TO_DO)
  deadline = models.DateField()
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  project = models.ForeignKey(Project, on_delete=models.CASCADE)
  assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tasks')

  @property
  def get_status_name(self):
    return self.Status(self.status).name.title()
  
  def __string__(self):
    return self.description

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Commit(models.Model):
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  task = models.ForeignKey(Task, on_delete=models.CASCADE)
  note = models.TextField()

  def __string__(self):
    return self.note

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})

webformat/ticketing/views/tasks.py
from ast import For
from hashlib import new
from multiprocessing import context
from pydoc import describe
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from ticketing.models import Project, Task, Commit
from django.conf import settings
from django.contrib.auth import get_user_model
from . import get_projects
from ticketing.forms import FormCreateTask


# GET all tasks
def get_tasks(request):
  context = {"tasks": Task.objects.filter(assignees__in=[request.user])}
  return render(request, "task/index.html", context)

# POST update task
def update_task(request, pk):
  task = Task.objects.get(pk=pk)
  if request.method == "POST":
    form = request.POST
    print(form)
    task.description = form.get("description")
    task.status = form.get("status")
    # task.deadline = form.get("deadline")
    task.save()
    task.assignees.set(form.getlist("developer"))
    return redirect(get_projects)
  developers = get_user_model().objects.filter(role = 3)
  task_form = FormCreateTask()
  context = {
    "task": task,
    "task_form": task_form,
    "developers": developers,
    "logged_user": request.user
  }
  return render(request, "task/edit.html", context)

# GET get commits
def commits_task(request, pk):
  task = Task.objects.get(pk=pk)
  if request.method == "POST":
    form = request.POST
    commit = Commit(creator=request.user, note=form.get("comment"), task=task)
    commit.save()
  commits = task.commit_set.all()
  context = {
    "task": task,
    "commits": commits
  }
  return render(request, "task/show.html", context)

webformat/templates/task/edit.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block content %}

  <a href="/projects">Torna indietro</a>
  <h2>Task {{ task.description }}</h2>
  <div>Assegnati:</div>
  <form action="" method="post">{% csrf_token %}
    <p>
      <label for="id_name">Name:</label>
      <input type="text" name="description" maxlength="100" required="" id="id_description" value="{{ task.description }}">
    </p>
    <!-- <p>
      <label for="id_deadline">Deadline:</label>
      <input type="date" name="deadline" id="id_deadline" value="{{ task.deadline }}">
    </p> -->
    <label for="id_status">Status:</label>
    <select name="status" id="id_status">
      <option value="1">TO_DO</option>
      <option value="2">IN_PROGRESS</option>
      <option value="3">STAGE</option>
      <option value="4">DONE</option>
    </select>
    <table class="table">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in developers %}
          <tr>
            <td>{{ employee.first_name }}</td>
            <td>{{ employee.last_name }}</td>
            <td>
              <input type="checkbox" name="developer" value="{{ employee.id }}" {% if employee in task.assignees.all %} checked {% endif %}>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <input type="submit" value="Modifica">
  </form>
{% if user.role == 1 %}
  <a href="/teams/{{ team.id }}/edit">Modifica team</a>
  <br><br>
  <a href="/teams/{{ team.id }}/delete">Elimina team</a>
{% endif %}
{% endblock %}

webformat/templates/task/index.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block content %}

  <a href="/">home</a>

  <h4>Tasks:</h4>

  <table class="table">
    <tr>
      <th>Description</th>
      <th>Project</th>
      <th>Status</th>
      <th>Deadline</th>
      <th>Commits</th>
    </tr>
    {% for task in tasks %}
    <tr>
      <td>{{ task.description }}</td>
      <td>{{ task.project.name }}</td>
      <td>{{ task.get_status_name }}</td>
      <td>{{ task.deadline }}</td>
      <td>
        <form action="{{ task.id }}/commits" method="get">
          <input type="submit" value="Dettagli">
        </form>
      </td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

webformat/templates/task/show.html
{% extends "base.html" %}

{% block title %}Tasks{% endblock %}

{% block content %}

  <a href="/tasks">Torna indietro</a>

  <h4>Tasks:</h4>

  <table class="table">
    <tr>
      <th>Description</th>
      <th>Project</th>
      <th>Status</th>
      <th>Deadline</th>
    </tr>
    <tr>
      <td>{{ task.description }}</td>
      <td>{{ task.project.name }}</td>
      <td>{{ task.get_status_name }}</td>
      <td>{{ task.deadline }}</td>
    </tr>
  </table>

  <table class="table">
    <tr>
      <th>Author</th>
      <th>Message</th>
    </tr>
    {% for commit in commits %}
    <tr>
      <td>{{ commit.creator.first_name }} {{ commit.creator.last_name }}</td>
      <td>{{ commit.note }}</td>
    </tr>
    {% endfor %}
  </table>

  <form action="" method="post">
    {% csrf_token %}
    <input type="text" name="comment" id="id_comment" placeholder="Messaggio...">
    <input type="submit" value="Commenta">
  </form>

{% endblock %}