webformat/employees/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

webformat/webformat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('admin/', admin.site.urls),
    path('', include('ticketing.urls')),
    path("accounts/", include("employees.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

webformat/ticketing/models.py
from msilib.schema import Registry
from pyexpat import model
from statistics import mode
from django.db import models
from django.conf import settings
from django.urls import reverse
from enum import IntEnum

# Create your models here.

class Team(models.Model):
  members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='teams')
  name = models.CharField(max_length=30)
  description = models.TextField(null=True)

  def __string__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Project(models.Model):
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  pm = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pm')
  name = models.CharField(max_length=30)
  description = models.TextField(null=True)

  def __string__(self):
    return self.name

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Task(models.Model):

  class Status(IntEnum):
    TO_DO = 1
    IN_PROGRESS = 2
    STAGE = 3
    DONE = 4

    @classmethod
    def choices(cls):
      return [(key.value, key.name) for key in cls]

  description = models.CharField(max_length=30)
  status = models.IntegerField(choices=Status.choices(), default=Status.TO_DO)
  deadline = models.DateField()
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  project = models.ForeignKey(Project, on_delete=models.CASCADE)
  assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tasks')

  @property
  def get_status_name(self):
    return self.Status(self.status).name.title()
  
  def __string__(self):
    return self.description

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})


class Commit(models.Model):
  creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  task = models.ForeignKey(Task, on_delete=models.CASCADE)
  note = models.TextField()

  def __string__(self):
    return self.note

  def get_absolute_url(self):
    return reverse("nomeRoot", kwargs={"pk": self.pk})

webformat/ticketing/views/projects.py
from ast import For
from hashlib import new
from multiprocessing import context
from pydoc import describe
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from ticketing.models import Project, Task
from django.conf import settings
from django.contrib.auth import get_user_model
from ticketing.forms import FormCreateProject, FormCreateTask

# GET all projects
def get_projects(request):
  context = {"projects": Project.objects.all()}
  return render(request, "project/index.html", context)

# GET specific project
def get_project(request, pk):
  project = Project.objects.get(pk=pk)
  tasks = Task.objects.filter(project=project)
  task_form = FormCreateTask()
  developers = get_user_model().objects.filter(role = 3)
  context = {
    "task_form": task_form,
    "project": project,
    "tasks": tasks,
    "developers": developers,
    "logged_user": request.user
  }
  return render(request, "project/show.html", context)

# POST create task
def create_task(request, pk):
  form = request.POST
  print(form)
  project = Project.objects.get(pk=pk)
  new_task = Task(project=project, description=form.get("description"), status=form.get("status"), deadline=form.get("deadline"), creator=request.user)
  new_task.save()
  new_task.assignees.set(form.getlist("assignees"))
  return redirect(get_project, pk)

# POST delete task
def delete_task(request, pk):
  form = request.POST
  task = Task.objects.get(pk=form.get("task_id"))
  task.delete()
  return redirect(get_project, pk)

# GET create a new project
def new_project(request):
  if request.method == "POST":
    form = request.POST
    new_project = Project(name = form.get("name"), description = form.get("description"))
    new_project.save()
    new_project.members.set(form.getlist("developer"))
    return redirect(get_projects)
  else:
    form = FormCreateProject()
    pms = get_user_model().objects.filter(role = 2)
  context = {
    "form": form,
    "pms": pms
  }
  return render(request, "project/new.html", context)

# GET edit a project
def edit_project(request, pk):
  project = Project.objects.get(pk=pk)
  if request.method == "POST":
    form = request.POST
    project.name = form.get("name")
    project.description = form.get("description")
    project.save()
    project.members.set(form.getlist("developer"))
    return redirect(get_projects)
  else:
    form = FormCreateProject()
    pms = get_user_model().objects.filter(role = 2)
  context = {
    "form": form,
    "pms": pms,
    "project": project
  }
  return render(request, "project/edit.html", context)

# POST delete project
def delete_project(request, pk):
  project = Project.objects.get(pk=pk)
  project.delete()
  return redirect(get_projects)

webformat/templates/project/edit.html
{% extends "base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}

  <a href="/projects">Torna indietro</a>
  <h2>Progetto {{ project.name }}</h2>
  <form action="" method="post">{% csrf_token %}
    <p>
      <label for="id_name">Name:</label>
      <input type="text" name="name" maxlength="30" required="" id="id_name" value="{{ project.name }}">
    </p>
    <p>
      <label for="id_description">Description:</label>
      <textarea name="description" cols="40" rows="10" required="" id="id_description">{{ project.description }}</textarea>
    </p>
    <label for="pm">Pm:</label>
    <select name="pm" required="" id="id_pm">
      {% for pm in pms %}
        <option value="{{ pm.id }}" {% if project.pm == pm %} selected {% endif %} >{{ pm }}</option>
      {% endfor %}
    </select>
  {% if user.role == 1 %}
  <input type="submit" value="Modifica progetto">
  {% endif %}
  </form>
{% endblock %}

webformat/templates/project/index.html
{% extends "base.html" %}

{% block title %}Teams{% endblock %}

{% block content %}

<a href="/">Home</a>

<h2>Projects</h2>

{% if user.role == 1 %}
<a href="/projects/new">Crea un nuovo Progetto</a>
</br></br>
{% endif %}
{% for project in projects %}
<div style="border: 1px solid black;">
  <h3 style="border-bottom: 1px solid gray;">{{ project.name }}</h3>
  <p>{{ project.description }}</p>
  <form action="/projects/{{ project.id }}" method="get">
    <input type="submit" value="Dettaglio">
  </form>
</div>
{% endfor %}

{% endblock %}

webformat/templates/project/new.html
{% extends "base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
<a href="/projects">Torna indietro</a>
<h2>New project</h2>
<form action="" method="post">
  {% csrf_token %}
  <label for="pm">Pm:</label>
  <select name="pm" required="" id="id_pm">
    <option value="" selected="">---------</option>
    {% for pm in pms %}
      <option value="{{ pm.id }}">{{ pm }}</option>
    {% endfor %}
  </select>
  <br><br>
  {{ form.as_p }}
  <input type="submit" value="Crea">
</form>
{% endblock %}

webformat/templates/project/show.html
{% extends "base.html" %}

{% block title %}Teams{% endblock %}

{% block content %}

  <a href="/projects">Torna indietro</a>
  <h2>Progetto {{ project.name }}</h2>
  <h4>Descrizione:</h4>
  <p>
    {{ project.description }}
  </p>
  <table class="table">
    <thead>
      <tr>
        <th>Task</th>
        <th>Status</th>
        <th>Deadline</th>
        {% if user.role == 1 %}
        <th>Details</th>
        <th>Delete</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <td>{{ task.description }}</td>
          <td>{{ task.get_status_name }}</td>
          <td>{{ task.deadline }}</td>
          {% if user.role == 1 %}
          <td>
            <form action="/tasks/{{ task.id }}" method="get">{% csrf_token %}
              <input type="submit" value="Dettagli">
            </form>
          </td>
          <td>
            <form action="{{ project.id }}/delete_task" method="post">{% csrf_token %}
              <input type="hidden" name="task_id", value="{{ task.id }}">
              <input type="submit" value="Elimina">
            </form>
          </td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% if user.role == 2 %}
<div>Nuovo task:</div>
<form action="{{ project.id }}/create_task" method="post">
  {% csrf_token %}
  {{ task_form.as_p }}
  <input type="date" name="deadline" id="id_deadline">
  <table>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Add</th>
    </tr>
    {% for dev in developers %}
    <tr>
      <td>{{ dev.first_name }}</td>
      <td>{{ dev.last_name }}</td>
      <td><input type="checkbox" name="developer" value="{{ dev.id }}"></td>
    </tr>
    {% endfor %}
  </table>
  <input type="submit" value="Crea">
</form>
{% endif %}
{% if user.role == 1 %}
  <a href="/projects/{{ project.id }}/edit">Modifica progetto</a>
  <br><br>
  <a href="/projects/{{ project.id }}/delete">Elimina progetto</a>
{% endif %}
{% endblock %}